import './globals.css'

import NavBar from '../components/NavBar'

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className="bg-zinc-50">
        <div className="min-h-screen flex flex-col">
        <NavBar />
        <div className="flex-1">
          {children}
        </div>
        </div>
      </body>
    </html>
  )
}
