import './globals.css'

import { Analytics } from '@vercel/analytics/react'
import NavBar from '../components/NavBar'
import Disclaimer from '../components/disclaimer';

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className="bg-primary">
        <Disclaimer />
        <div className="min-h-screen flex flex-col">
          <NavBar />
          <div className="flex-1">
            {children}
            <Analytics />
          </div>
        </div>
      </body>
    </html>
  )
}
